---
options:
  max-warnings: 50
files:
  include: 'src/**/*.s+(a|c)ss'
rules:
  leading-zero: 0
  no-url-domains: 0
  no-url-protocols: 0
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: camelcase
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: camelcase
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
      convention: camelcase
  class-name-format:
    - 2
    - allow-leading-underscore: false
      convention: camelcase
  nesting-depth:
    - 2
    - max-depth: 3
