[workspace.package]
version = "0.1.0"
edition = "2021"
description = "Simple beer inventory display"
readme = "README.md"
authors = ["Cian Butler <butlerx@notthe.cloud>"]
repository = "https://github.com/butlerx/invbeertory"
license = "MIT"
keywords = ["beer", "yew", "rust", "web", "inventory", "display", "google-sheets", "wasm"]
categories = ["wasm", "web", "beer", "inventory", "display", "simple"]

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1"
